package com._36wu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.12
 * 2017-04-02T23:45:29.695+08:00
 * Generated source version: 3.0.12
 * 
 */
@WebService(targetNamespace = "http://www.36wu.com/", name = "WeatherServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherServiceSoap {

    /**
     * <h3>支持城市列表</h3>
     */
    @WebResult(name = "GetAreaListResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetAreaList", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetAreaList")
    @WebMethod(operationName = "GetAreaList", action = "http://www.36wu.com/GetAreaList")
    @ResponseWrapper(localName = "GetAreaListResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetAreaListResponse")
    public com._36wu.ResultOfListOfArea getAreaList(
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>生活气象指数</h3>
     */
    @WebResult(name = "GetWeatherIndexResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherIndex", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherIndex")
    @WebMethod(operationName = "GetWeatherIndex", action = "http://www.36wu.com/GetWeatherIndex")
    @ResponseWrapper(localName = "GetWeatherIndexResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherIndexResponse")
    public com._36wu.ResultOfWeatherIndex getWeatherIndex(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        java.lang.String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>经纬度智能地区未来一周气象</h3>
     */
    @WebResult(name = "GetMoreWeatherByLocationResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeatherByLocation", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByLocation")
    @WebMethod(operationName = "GetMoreWeatherByLocation", action = "http://www.36wu.com/GetMoreWeatherByLocation")
    @ResponseWrapper(localName = "GetMoreWeatherByLocationResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByLocationResponse")
    public com._36wu.ResultOfMoreWeather getMoreWeatherByLocation(
        @WebParam(name = "lat", targetNamespace = "http://www.36wu.com/")
        float lat,
        @WebParam(name = "lng", targetNamespace = "http://www.36wu.com/")
        float lng,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>经纬度智能地区实时气象</h3>
     */
    @WebResult(name = "GetWeatherByLocationResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherByLocation", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByLocation")
    @WebMethod(operationName = "GetWeatherByLocation", action = "http://www.36wu.com/GetWeatherByLocation")
    @ResponseWrapper(localName = "GetWeatherByLocationResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByLocationResponse")
    public com._36wu.ResultOfTodayWeather getWeatherByLocation(
        @WebParam(name = "lat", targetNamespace = "http://www.36wu.com/")
        float lat,
        @WebParam(name = "lng", targetNamespace = "http://www.36wu.com/")
        float lng,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>实时气象</h3>
     */
    @WebResult(name = "GetWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeather")
    @WebMethod(operationName = "GetWeather", action = "http://www.36wu.com/GetWeather")
    @ResponseWrapper(localName = "GetWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherResponse")
    public com._36wu.ResultOfTodayWeather getWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        java.lang.String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>IP智能地区未来一周气象</h3>
     */
    @WebResult(name = "GetMoreWeatherByIpResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeatherByIp", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByIp")
    @WebMethod(operationName = "GetMoreWeatherByIp", action = "http://www.36wu.com/GetMoreWeatherByIp")
    @ResponseWrapper(localName = "GetMoreWeatherByIpResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherByIpResponse")
    public com._36wu.ResultOfMoreWeather getMoreWeatherByIp(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        java.lang.String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>IP智能地区实时气象</h3>
     */
    @WebResult(name = "GetWeatherByIpResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetWeatherByIp", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByIp")
    @WebMethod(operationName = "GetWeatherByIp", action = "http://www.36wu.com/GetWeatherByIp")
    @ResponseWrapper(localName = "GetWeatherByIpResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetWeatherByIpResponse")
    public com._36wu.ResultOfTodayWeather getWeatherByIp(
        @WebParam(name = "ip", targetNamespace = "http://www.36wu.com/")
        java.lang.String ip,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>未来一周气象</h3>
     */
    @WebResult(name = "GetMoreWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetMoreWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeather")
    @WebMethod(operationName = "GetMoreWeather", action = "http://www.36wu.com/GetMoreWeather")
    @ResponseWrapper(localName = "GetMoreWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetMoreWeatherResponse")
    public com._36wu.ResultOfMoreWeather getMoreWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        java.lang.String district,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );

    /**
     * <h3>历史气象查询</h3>
     */
    @WebResult(name = "GetHistoricalWeatherResult", targetNamespace = "http://www.36wu.com/")
    @RequestWrapper(localName = "GetHistoricalWeather", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetHistoricalWeather")
    @WebMethod(operationName = "GetHistoricalWeather", action = "http://www.36wu.com/GetHistoricalWeather")
    @ResponseWrapper(localName = "GetHistoricalWeatherResponse", targetNamespace = "http://www.36wu.com/", className = "com._36wu.GetHistoricalWeatherResponse")
    public com._36wu.ResultOfListOfHistoricalWeather getHistoricalWeather(
        @WebParam(name = "district", targetNamespace = "http://www.36wu.com/")
        java.lang.String district,
        @WebParam(name = "start", targetNamespace = "http://www.36wu.com/")
        java.lang.String start,
        @WebParam(name = "end", targetNamespace = "http://www.36wu.com/")
        java.lang.String end,
        @WebParam(name = "authkey", targetNamespace = "http://www.36wu.com/")
        java.lang.String authkey
    );
}
